on:
  push:
    branches:    
      - '*/*'       # matches every branch containing a single '/'
      - '!main'   # excludes master

jobs:
  on_build_actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Tests
        run: python api_test.py
